[package]
name = "simple_sqlite_clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "grep"
path = "src/main.rs"


[[bin]]
name = "ls"
path = "src/main.rs"



[dependencies]
